### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Gloria-hue** [erykjj/jwpublib#1]
Hello erykjj?
great job with this tool. I have no issue with-it except a very basic question. How do I use it?
any simple ,clear instructions for a  non-developer?

**Comment by erykjj** [comment]
I am assuming you are asking about how to add this to JW Library...

1. In all cases, you need to have the JW Library app installed.
2. Then, download the desired _.jwpub_ add-on publication.
3. Generally, by **tapping/double-clicking the downloaded file**, it should be automatically added to JW Library. It will be found in the **Library** section -> **DOWNLOADED** tab -> **Guidelines** category.

If that doesn't answer your question, let me know what platform you're using (Windows, iPhone/iPad, Android phone/tablet) and where you're "stuck".

**Comment by Gloria-hue** [comment]
Thank you for the response. It works well now.

**Comment by Gloria-hue** [comment]
It works very well, thanks

**Comment by erykjj** [comment]
Thank you, @Gloria-hue . The sources for _Strong's_ and _Vine's_ that I found online are far from perfect, but the gist is there :-)
