### ISSUE TITLE
BRS in Spanish

### ISSUE THREAD

**Issue by yuniermv** [erykjj/jwpublib#12]
Brother, I made some small design changes to BRS in Spanish to make it look more like the current publications. You can count on me if you want.
![Screenshot_20230508-115944.png](https://user-images.githubusercontent.com/120569483/236872347-cae0b3bd-8876-4806-93c5-84470cf81f82.png)

**Comment by erykjj** [comment]
Gracias @yuniermv . Aprecio las ideas/sugerencias. Lo tomaré en cuenta.

No me molesta que se modifiquen y/o re-distribuyan las publicaciones que comparto, siempre y cuando se respete la licencia, en particular sobre dejar intactos los derechos de autor de las publicaciones y el enlace a JWPubLib ;-)

**Comment by yuniermv** [comment]
Muy bien. Estamos en contacto. Que bueno que hablas español.
Aqui te adjunto el archivo por si lo deseas subir.
Saludos desde Cuba.

**Comment by erykjj** [comment]
Hola @yuniermv  
Estoy actualizando el archivo de las lecturas bíblicas: https://github.com/erykjj/jwpublib#bible-reading-schedules-v2

**Comment by yuniermv** [comment]
Muchas gracias hermano querido.
