### ISSUE TITLE
Bible Reading Schedule - English

### ISSUE THREAD

**Issue by cienypico** [erykjj/jwpublib#13]
Is it possible to get the English version of the Bible reading schedule? Thank you

**Comment by erykjj** [comment]
Hi @cienypico ,
The English (E) version of BRS is the first in the list of [attached documents](https://github.com/erykjj/jwpublib/releases/tag/BRS_1.4):

![2023-05-22_07-05-19](https://github.com/erykjj/jwpublib/assets/107011362/f1a8e5b7-55b7-4456-ba9e-cc7877888870)

**Comment by cienypico** [comment]
Thank you
