### ISSUE TITLE
BRS in German please 🙏🏻

### ISSUE THREAD

**Issue by Radieserlbrot** [erykjj/jwpublib#14]
Dear Brother,
maybe it is possible for you to translate the BRS in German, please? Me and surely others would definitely appreciate it. Thanks for your work and 
All the best
Peer

**Comment by erykjj** [comment]
Hi @Radieserlbrot ,
I would gladly do it, but I need someone to help with translation. There are only a few terms. Do you think you could help with translating from English to German?

**Comment by Radieserlbrot** [comment]
Hi, yes, I guess this should be possible. I would be glad to help

**Comment by erykjj** [comment]
Great! Please translate the following into German.

```
Bible Reading Schedules
Canonical
Chronological
Commenced
Completed
Day
Month
Months
More information and updates
Version
Week
Year
Years
as found in the Bible
by time of completion of writing
in order of historical occurrence
```

**Comment by Radieserlbrot** [comment]
Bible Reading Schedules = Bibellesepläne
Canonical = kanonisch
Chronological = chronologisch
Completed (for the Completed 6 Months etc. schedules) = nach Fertigstellung

Commenced = begonnen
Completed (meaning start of reading this schedule) = abgeschlossen

Day = Tag
Month = Monat
Months = Monate
More information and updates = Weitere Informationen und Updates
Version = Version
Week = Woche
Year = Jahr
Years = Jahre
as found in the Bible = gemäß der Reihenfolge in der Bibel
by time of completion of writing = gemäß der Fertigstellung des Bibelbuchs
in order of historical occurrence = gemäß der historischen Abfolge

**Comment by Radieserlbrot** [comment]
Please note there is a difference in the usage of the two completed occurrences. When used for the start date, it is "begonnen". When used for four completed schedules, it is "nach Fertigstellung"

**Comment by erykjj** [comment]
Please check:
```
Bible Reading Schedules	Bibellesepläne
Canonical	Kanonisch
Chronological	Chronologisch
Commenced	Begonnen
Completed	Abgeschlossen
Completed	Nach Fertigstellung
Day	Tag
English	Deutsch
English	German
Month	Monat
Months	Monate
More information and updates	Weitere Informationen und Updates
Version	Version
Week	Woche
Year	Jahr
Years	Jahre
as found in the Bible	gemäß der Reihenfolge in der Bibel
by time of completion of writing	emäß der Fertigstellung des Bibelbuchs
in order of historical occurrence	gemäß der historischen Abfolge
```
One of the "Completed" terms should describe the _order_ of the reading: by time of completion of writing (in contrast with Canonical and Chronological). Is that what "Nach Fertigstellung" refers to?

**Comment by Radieserlbrot** [comment]
there were some small mistakes. I have corrected it:

Bible Reading Schedules	Bibellesepläne
Canonical	kanonisch
Chronological	chronologisch
Commenced	Begonnen
Completed	Abgeschlossen
Completed	nach Fertigstellung
Day	Tag
English	Deutsch
English	German
Month	Monat
Months	Monate
More information and updates	Weitere Informationen und Updates
Version	Version
Week	Woche
Year	Jahr
Years	Jahre
as found in the Bible	gemäß der Reihenfolge in der Bibel
by time of completion of writing	gemäß der Fertigstellung des Bibelbuchs
in order of historical occurrence	gemäß der historischen Abfolge

And yes, you understood the thing with the "completed" terms correctly

**Comment by erykjj** [comment]
OK, very good.
Does it matter much if "kanonisch" is capitalized? I use it as a category title (first word) to identify the type of the schedule. That's why I thought to make it capital???

**Comment by Radieserlbrot** [comment]
I guess this should be fine, too

**Comment by erykjj** [comment]
Thank you for your help!
You can find the archive here: https://github.com/erykjj/jwpublib/releases/tag/BRS_1.4

Always open to feedback, my brother ;-)

**Comment by Radieserlbrot** [comment]
Very well done, thanks a lot. Have already been promoting it to my field service partner today :)
