### ISSUE TITLE
Convention notebook

### ISSUE THREAD

**Issue by cienypico** [erykjj/jwpublib#15]
Thank you - I have your 2023 RC convention notebook - just one query - how are notes saved? Are they saved in JW Library - specifically what happens if I were to accidentally delete the notebook? Are the notes saved anywhere where they can be recovered. Thank you, again.

**Comment by erykjj** [comment]
Hi @cienypico , the "2023 RC convention notebook" is not  from this repo. Perhaps you were wanting to post here: https://github.com/livrasand/JWPUB-Catalog

In any case, you can use my [JWLManager](https://github.com/erykjj/jwlmanager) app to examine the contents of annotation fields stored by JW Library. You can export them to back them up, should you wish to do so. ;-)

**Comment by cienypico** [comment]
Thank you, erykjj. Sorry to have bothered you. I will have a look at the JWLManager but suspect it might be a little beyond my ability.
