### ISSUE TITLE
Very old publications in JWLibrary. (I mean, a century old publications)

### ISSUE THREAD

**Issue by mynameisjuliano** [erykjj/jwpublib#16]
I saw in the Internet Archive that there was the Photodrama of Creation apparently available to everyone, was wondering if the old books could be archived too? It's mostly for historical reason, though, though I'm just curious if that's possible since there will be Bible citations there and what not. Also thank you for the great additions to our library, it will really be handy to study with these, thank you very much!

**Comment by erykjj** [comment]
Hi @mynameisjuliano ,
Thanks for your inquiry. In theory, those older publications could be included. But, weighing the practical value of that, I would not do it.
