### ISSUE TITLE
Can we get in touch?

### ISSUE THREAD

**Issue by gsb1214** [erykjj/jwpublib#17]
Hi. I’d like to email you to ask you something about the possibility of creating the Watchtower Publications Index for JW Library.

**Comment by erykjj** [comment]
Hi @gsb1214 , I see you joined Github just so you could contact me :-)

Regarding your question, the source material is copyrighted. So, unless you plan on compiling your own list of references, you would need to get permission from the authors to create such an index.

Eryk

**Comment by gsb1214** [comment]
Hi, Erik. Yes, I joined so that I could contact you. I can use the Index but on the Watchtower Online Library. The thing is that I live in Cuba and internet signal is bad and expensive. So going online whenever I need to look something up is not practical. So I’ve looking for years how to get it but no success. Enviado desde mi iPhoneEl 21 jun. 2023, a la(s) 3:07 p.m., Eryk J. ***@***.***> escribió:﻿
Hi @gsb1214 , I see you joined Github just so you could contact me :-)
Regarding your question, the source material is copyrighted. So, unless you plan on compiling your own list of references, you would need to get permission from the authors to create such an index.
Eryk
