### ISSUE TITLE
 Vine's Expository Dictionary in KJV and Strong Bible

### ISSUE THREAD

**Issue by XcXblythe26** [erykjj/jwpublib#18]
Hi, erykjj, whenever we tap any Strongs Number in Bible KJV, I'd like the Vine's Expository Dictionary to show with the Strongs Dictionary. It would be nice to add.

**Comment by XcXblythe26** [comment]
Also Hebrew in Vine's Expository Dictionary is nice to add too.

**Comment by erykjj** [comment]
Hi @XcXblythe26 ,

Thanks for your suggestions.

Vine's is only a Greek dictionary (of "New Testament" words). It is already cross-linked in Strong's (again, Greek terms only). You'll find a link icon at the end of the definition, which will take you to the corresponding Vine's entry/entries.

![2023-06-25_08-39-56](https://github.com/erykjj/jwpublib/assets/107011362/07113049-fceb-413c-a7c2-12472264284a)
![2023-06-25_08-40-59](https://github.com/erykjj/jwpublib/assets/107011362/459658cd-c001-4641-85de-0b42099814e6)

**Comment by XcXblythe26** [comment]
I didn't see that, I thought that was just a design. 🤭

**Comment by XcXblythe26** [comment]
Does Vine's has Hebrew?

**Comment by erykjj** [comment]
> Does Vine's has Hebrew?

No, it doesn't. There may be other more extensive Hebrew dictionaries out there, but, for now, I will not be adding any. I chose Strong's and Vine's because they are quite often used as authoritative sources.

**Comment by XcXblythe26** [comment]
Thank you!

**Comment by XcXblythe26** [comment]
I

**Comment by XcXblythe26** [comment]
Hello, brother, I saw this on _Insight_ on [here:](https://www.jw.org/finder?srcid=jwlshare&wtlocale=E&prefer=lang&docid=1200002781&par=6) 

“Of the noun a·gaʹpe and the verb a·ga·paʹo, **Vine’s Expository Dictionary of Old and New Testament Words** says: “Love can be known only from the actions it prompts. God’s love is seen in the gift of His Son, I John 4:9, 10. But obviously this is not the love of complacency, or affection, that is, it was not drawn out by any excellency in its objects, Rom. 5:8. It was an exercise of the Divine will in deliberate choice, made without assignable cause save that which lies in the nature of God Himself, cp. Deut. 7:7, 8.”—1981, Vol. 3, p. 21”

Could there be a Hebrew version in another book, couldn't there?

**Comment by erykjj** [comment]
Find me a freely-downloadable source online (XML, JSON or similar) and I'll have a look.

**Comment by XcXblythe26** [comment]
Let me see, brother, I will came back after I see one. 

😗🎵 _looking for codes in websites_ 

Also, I know that this conversation will be a kind of confidential. Can I contact you in another way?

**Comment by XcXblythe26** [comment]
Currently find a book, I am eager to make an XML file for this, don't worry I use AI to do this work. Can you give me specific format of tags to make an XML.

Example for this: “

**Comment by XcXblythe26** [comment]
Currently find a book, I am eager to make an XML file for this, don't worry I use AI to do this work. Can you give me specific format of tags to make an XML.

Example for this: 
“ABOMINATION - (verb) ta'ab (תעב , 8581), “to abhor, treat as abhorrent, cause to be an abomination, act abominably.” This verb occurs 21 times, and the first occurrence is in Deut. 7:26: “Neither shalt thou bring an abomination into thine house.…””

**Comment by XcXblythe26** [comment]
There are only 455 pages of Hebrew dictionary on this book—I found. Also, the Greek is the same on VED. I see also the usage of listing like (A-1, B-1, 1, etc.)

**Comment by erykjj** [comment]
I'll get back to you later.

**Comment by XcXblythe26** [comment]
Okay, I'll wait, brother.
