### ISSUE TITLE
PERSONAL instead of Personal

### ISSUE THREAD

**Issue by XcXblythe26** [erykjj/jwpublib#19]
Hi, brother, can you change the “**Personal**” into “**PERSONAL**” in the Guidelines. 😁 I know that is just a small changes but that cost a lot of effort. Thank you!

![Screenshot_20230625_211037_JW Library](https://github.com/erykjj/jwpublib/assets/137697011/62e2ef50-d1c0-4a26-94a4-8d153ccceb8d)

I also see the Song of Solomon in BRS. Please make it “Ca” which is its abbreviation. If you're wondering it means “Canticles,” and it used worldwide including _NWT_.

**Comment by erykjj** [comment]
Hi @XcXblythe26 ,

RE "PERSONAL", I can see your reasoning for it. It will be implemented in all future versions of each archive.

**Comment by erykjj** [comment]
As for the Song of Solomon, I use the "standard" abbreviations (like "Gen.", "Deut.", "Matt." - or "Song of Sol." in this case). "Ca" is the "official" book abbreviation (usually only 2 or 3 characters, like "Ge", "Dt", "Mt"). I find the "standard" to be more understandable, while still being abbreviated. However, if there is "widespread" support/preference for the "official", it can be implemented.

**Comment by XcXblythe26** [comment]
Oh, I see. Thank you, brother.

**Comment by erykjj** [comment]
> Hi @XcXblythe26 ,
> 
> RE "PERSONAL", I can see your reasoning for it. It will be implemented in all future versions of each archive.

Archives updated with this small adjustment:
https://github.com/erykjj/jwpublib/releases/tag/VED_2.0
https://github.com/erykjj/jwpublib/releases/tag/Str_2.0

**Comment by XcXblythe26** [comment]
You really listen, brother. I appreciated it!
