### ISSUE TITLE
Possibly add Enjoy Life Forever?

### ISSUE THREAD

**Issue by PhillyBoi1111** [erykjj/jwpublib#2]
I have a study with a young brother, and am finding it hard to have my meeting notes, and notes for the study in 2 separate locations. At the moment I have to do my meeting prep in a pdf program, and my study notes in JW Library so that the notes don't conflict. Would you be able to add the enjoy life forever book as a separate publication in a different tab so that we can have separate notes for them?

**Comment by erykjj** [comment]
Do you mean like having two copies of the same publication, each one with its own highlighting and notes? That _is_ doable, but 1) the copy wouldn't be updated and 2) it touches on copyrights.

Have you considered/tried adding tags to your notes? You could tag one set as "Personal" and the other "Study" (or even with the name of the person). You can use my JWLManager to export/import/back-up/delete notes.

**Comment by PhillyBoi1111** [comment]
Yeah that's exactly what I mean, I'm glad you understand what I was trying to say. Yeah I've tried that in the past, but I have a lot of study notes, I usually make multiple notes per paragraph for the meetings so it gets very hard to see the difference between the notes quickly when I'm trying to bring out a point to him. For the meetings it doesn't interfere too much as I have the time to find the right note, but it's very difficult during the study so I've had to switch to a pdf. Which is also difficult in itself with not being able to click on the scriptures or extra study materials. Yeah thank you for that program, I use it all the time with syncing my notes between my surface pro and desktop 😁

**Comment by PhillyBoi1111** [comment]
Sorry forgot to comment on what you said about doing it. The fact that it won't be updated is ok, I don't imagine that there's too many differences between publications when they update it. When you say it touches on copyrights, would you mind explaining that further? From my limited knowledge I can't see any problem with it as they already provide the publication in the app, it's just making a duplicate of it. But if I'm missing something or if you don't feel it's a good thing to do, then I perfectly understand. Just thought it might be an easier way for myself and others who might be in a similar situation, but I'm happy to keep using a pdf instead 😀

**Comment by erykjj** [comment]
How is this for a work-around?

![2022-10-19_08-33-18](https://user-images.githubusercontent.com/107011362/196692066-05464ca1-5098-4990-a486-540334198db2.png)

To achieve this, you would have to export your notes and edit the {COLOR=} attribute. HOWEVER, and it's explained in the README, the app has a bug/feature that won't display the colored sticky notes if there is no associated highlighted text. To get around that, you also need to change the {LANG=} attribute to another language - strangely enough, the stickies _do_ show in other languages. The only drawback with this method is that if you access the notes from the Personal Study section, it will take you to the publication, but in the other language.

So, since my sample notes are in the Spanish Enjoy Life, I edited them changing {LANG=1} (Spanish) to {LANG=0} (English) and {COLOR=0} to {COLOR=1} and {COLOR=2}, depending on the tab. Then, import and delete the originals (in the Spanish publiation). Am I explaining myself? :-)

**Comment by erykjj** [comment]
As for the copyright issue, it boils down to the fact that to create a duplicate, even slightly modified (with a different id), I am modifying the source without permission.

**Comment by PhillyBoi1111** [comment]
Yeah that's definitely a work around, thank you for spending the time on finding a solution to that. I might give it a go if I'm feeling tech savvy, I don't really know too much about coding, but I really appreciate the time and effort you've put into that. That's ok, I understand, I don't want to negatively affect anyone's concious and ask them to do something they don't feel comfortable doing so that's all good brother. Thank you again for the time you've spent, I don't think I'll be able to figure out the coding method, but I sincerely appreciate the time you spent thinking of a better solution for me

**Comment by erykjj** [comment]
No coding required. Just editing the exported _JWL_Notes_ text file.

If you have a text editor with regular expression (regex) find/replace, you could do something like this:
**Find**: `===(.*?){LANG=0}{PUB=lff}(.*?){COLOR=0}{TAGS=Personal}(.*?)===` (change the language number from 0 - English - to whatever the language is that you are using; and change the "Personal" to whatever it is you tagged the notes you want to change color)
**Replace**: `===\1{LANG=1}{PUB=lff}\2{COLOR=2}{TAGS=Personal}\3===` (select the language and color value you want to give it)

So, for example, if your note header looked like this (a grey note in the English _lff_):
```
==={CAT=PUBLICATION}{LANG=0}{PUB=lff}{ISSUE=0}{DOC=1102021248}{BLOCK=5}{COLOR=0}{TAGS=Personal}{DATE=2022-10-19}===
```
It will look like this (a green note in the Spanish _lff_, which will also show up in your English book):
```
==={CAT=PUBLICATION}{LANG=1}{PUB=lff}{ISSUE=0}{DOC=1102021248}{BLOCK=5}{COLOR=2}{TAGS=Personal}{DATE=2022-10-19}===
```

**Comment by PhillyBoi1111** [comment]
I'm sorry, I really am trying to understand brother but at the moment I'm still a bit confused. I think I'll be able to edit the txt file but I'm still not fully understanding the language switching part. I don't want to bother you any further though, so I'll see if I can find someone more tech savvy than myself to walk me through your suggestion in person. Thank you for all of your time!

**Comment by PhillyBoi1111** [comment]
Hey I ended up finding a workaround, I have a surface pro as my main device, so I just used an emulator to run another instance of JW Library which worked well. I use the windows store version of JW Library for all my personal study and meeting prep now, and now use the android store version for my study. Thank you for all your help and suggestions, sorry that I wasn't able to follow along with it, but I appreciate your time brother :)
