### ISSUE TITLE
BRS in Dutch

### ISSUE THREAD

**Issue by Dosojin1** [erykjj/jwpublib#20]
Dear,

If it is possible, I would like to translate BRS into Dutch.

**Comment by erykjj** [comment]
Hi @Dosojin1 , I assume you are referring to translating the Bible Reading Schedules.

I would certainly appreciate that. Please translate the following strings:
```
Bible Reading Schedules

Commenced
Completed

Canonical
as found in the Bible

Chronological
in order of historical occurrence

Completion
by time of completion of writing

Day
Month
Months
Week
Year
Years

More information and updates
Version
```

**Comment by Dosojin1** [comment]
Here is the translation
```
Bible Reading Schedules
	Bijbel Lees Schema

Commenced
	Begonnen
Completed
	Voltooid

Canonical
	Canoniek
as found in the Bible
	zoals gevonden in de Bijbel

Chronological
	Chronologisch
in order of historical occurrence
	in historische volgorde

Completion
	Voltooiing
by time of completion of writing
	bij voltooiing van het schrijven

Day
	Dag
Month
	Maand
Months
	Maanden
Week
	Week
Year
	Jaar
Years
	Jaren

More information and updates
	Meer informatie en updates
Version
	Versie
```

**Comment by Dosojin1** [comment]
Perfect 😄, I'm looking forward to the updated version.

**Comment by erykjj** [comment]
@Dosojin1 there are some additional strings that need translating, please. Have a look here: https://github.com/erykjj/jwpublib/issues/21

**Comment by erykjj** [comment]
Thank you again @Dosojin1 !

Just one clarification, please:
Before you had "Bijbel Lees Schema" and now "Bijbelleesschema's". Which one is better for the title of the 'publication'?

**Comment by Dosojin1** [comment]
“Bijbelleesschema's” is much better. I’ve compared it with some publications.

> Thank you again @Dosojin1 !
> 
> Just one clarification, please: Before you had "Bijbel Lees Schema" and now "Bijbelleesschema's". Which one is better for the title of the 'publication'?

**Comment by erykjj** [comment]
OK. Thank you!
