### ISSUE TITLE
Open Bible when clicking

### ISSUE THREAD

**Issue by zbroinx** [erykjj/jwpublib#22]
Hi,
When I click the bible text to read, it does not open that bible part for that day to read.
Is possible to open bible when clicking?
![image](https://github.com/erykjj/jwpublib/assets/11558823/43b236ec-20b8-4f95-88d8-f1fee808087f)

**Comment by erykjj** [comment]
Hi Pedro,

Thank you for reporting. That's unusual...

Is it just this one text? Is it just for Joshua? Is it just on this schedule?

It is quite a large portion, perhaps it takes a while to "compile" into the side pane... What kind of device are you using?

Any and all information would be greatly appreciated ;-)

**Comment by zbroinx** [comment]
In a windows pc, I cannot open any bible link. It does not load any info.
In a surface go tablet (windows), takes some time but it loads.
In iphone it works correctly.

**Comment by erykjj** [comment]
![2023-08-09_18-10-56](https://github.com/erykjj/jwpublib/assets/107011362/40c25371-9017-4c14-b9bb-a4f843726039)

I just tried the Portuguese version on my Windows 10 setup and it worked.

What Bible translations do you have loaded/installled? Can you try removing the BRS publication, and adding it again, please?

**Comment by zbroinx** [comment]
Resolved.
