### ISSUE TITLE
Jwpub convert

### ISSUE THREAD

**Issue by MacPepper** [erykjj/jwpublib#23]
Hello,
Thank you very much for sharing.
Is there a solution for converting the Jwpub format to Epub?
Thanks in advance
Laurent

**Comment by erykjj** [comment]
Hi Laurent,
Sorry, I don't know of any way to convert between the two formats. But most of the publications on jw.org are already available as Epubs.

**Comment by MacPepper** [comment]
Hi Eryk,

Thanks for your reply.

I'm looking for a French version of Insight in Epub format, so that I can put it on a Kindle.

The only format I can find is Jwpub or PDF (difficult to convert too).

Thanks for your help

Laurent

Le 18 oct. 2023 à 16:59, Eryk J. ***@***.***> a écrit :


Hi Laurent,
Sorry, I don't know of any way to convert between the two formats. But most of the publications on jw.org are already available as Epubs.
