### ISSUE TITLE
VED & Str crashing on new version of JW Library for Windows

### ISSUE THREAD

**Issue by Pgwenlan** [erykjj/jwpublib#24]
Recently both the VED and Str have caused the windows version of jwlibrary to crash. This happens on a few computers.  On Android & Chromebook they work fine.

**Comment by erykjj** [comment]
Confirmed. Thank you for reporting. I don't use the Windows app, so I haven't noticed. Will see what can be done.

**Comment by Pgwenlan** [comment]
Perfect, thank you very much!

**Comment by erykjj** [comment]
@Pgwenlan , please check [VED_2.1](https://github.com/erykjj/jwpublib/releases/tag/VED_2.1) and [Str_2.1](https://github.com/erykjj/jwpublib/releases/tag/Str_2.1) and let me know if the issue is resolved.

**Comment by Pgwenlan** [comment]
They work great, thank you very much for your help!!

**Comment by erykjj** [comment]
> They work great, thank you very much for your help!!

Thank _you_ again for reporting!!
