### ISSUE TITLE
Ukrainian translation of BRS: Bible Reading Schedules

### ISSUE THREAD

**Issue by korotkiyYurii** [erykjj/jwpublib#26]
Ukrainian (DESTINATION LANGUAGE)
Графіки читання Біблії
Інформація
Версія
Більше інформації та оновлення 
Канонічні
В порядку, як розміщено в Біблії
Завершення написання
В порядку завершення написання
Хронологічні
В порядку історичних дій
Тематичний
Згрупований за типом викладу
Ця ціла частина може бути завершена за 18 місяців
Розпочато
Завершено
День
Тиждень
Місяць
Місяці
Рік
Роки
Історичні
Патріархи і Закон (П'ятикнижжя)
Історія Ізраїлю та Юди
Раннє християнство
Євангелія та Дії
Поетичні 
Поетичні книги
Пророчі 
Великі пророки
Малі пророки
Об'явлення
Листи
Листи Павла
Інші листи
Усі листи

**Comment by korotkiyYurii** [comment]
Hi Eryk 
I send you Ukrainian translation for BRS.
Will be happy to help with Timeline translation as well.
Many years ago I translated TMSWare on Russian and Ukrainian first time and supported this project during a years.

**Comment by erykjj** [comment]
Thank you.
Moved to https://github.com/erykjj/jwpublib/issues/27

**Comment by erykjj** [comment]
> Hi Eryk I send you Ukrainian translation for BRS. Will be happy to help with Timeline translation as well. Many years ago I translated TMSWare on Russian and Ukrainian first time and supported this project during a years.

Timeline will have to be English only, I'm afraid. I did not implement any framework for traslating it.

BUT, I could use some help with my other project [JWLManager](https://github.com/erykjj/jwlmanager). Russian needs completing. Once done, we could look at Ukrainian as well... The translation is on [Weblate](https://hosted.weblate.org/engage/jwlmanager/).
