### ISSUE TITLE
A couple of little changes in Ukrainian translation

### ISSUE THREAD

**Issue by korotkiyYurii** [erykjj/jwpublib#27]
Ukrainian (DESTINATION LANGUAGE)
Графіки читання Біблії
Інформація
Версія
Більше інформації та оновлення 
По канонічному порядку
В порядку, так, як розміщено в Біблії
По завершенню написання книги
В порядку завершення написання
Хронологічно
В порядку історичних дій
Тематичний
Згрупований за категоріями
Ця ціла частина може бути завершена за 18 місяців
Розпочато
Завершено
День
Тиждень
Місяць
Місяці
Рік
Роки
Історичні
Патріархи і Закон (П'ятикнижжя)
Історія Ізраїля та Юди
Раннє християнство
Євангелія та Дії
Поетичні 
Поетичні книги
Пророчі 
Великі пророки
Малі пророки
Об'явлення
Листи
Листи Павла
Інші листи
Усі листи

**Comment by korotkiyYurii** [comment]
Sorry, have found several wodrs that can be better.

**Comment by erykjj** [comment]
Thank you, @korotkiyYurii 
I will send you a pre-release soon to look over and double-check ;-)

**Comment by erykjj** [comment]
[BRS_K_pre-release.zip](https://github.com/erykjj/jwpublib/files/13874236/BRS_K_pre-release.zip)
Ok, unzip and try, and please let me know what needs changing.
Thank you!
