### ISSUE TITLE
Gen 6 is missing in chronological order (6 months) 

### ISSUE THREAD

**Issue by speedyalibaba** [erykjj/jwpublib#3]
1. Day: Gen 1-5
2. Day: Gen 7-10:5

**Comment by erykjj** [comment]
Excellent catch! Thank you for reporting. Please let me know of any others.

**Comment by erykjj** [comment]
Examining the chronological breakdown, I can see now that a lot more is missing :-(
I would like to get a more precise/correct source. I guess for now I may have to remove the chronological schedules altogether...

**Comment by erykjj** [comment]
Fixed in [BRS_1.2](https://github.com/erykjj/jwpublib/releases/tag/BRS_1.2)

**Comment by Godgethub** [comment]
Hi dear, first of all I wanted to thank you for the excellent work you have done. I wanted to ask you for info, how did you create the jwpub file? I have cards and notes from a theocratic school that I would like to transfer to jwlibrary
