### ISSUE TITLE
BRS in Hungarian

### ISSUE THREAD

**Issue by xrtxn** [erykjj/jwpublib#31]
Here are the strings translated, I did my best but it may not be perfect:
```
Hungarian (magyar)
Biblia olvasási ütemtervek
Információ
Verzió
További információ és frissítések
Könyvek sorrendje
ahogy a bibliában található
Befejezés dátuma
az írás befejezése szerint csoportosítva
Időrendi sorrendben
történelmi sorrend szerint csoportosítva
Tematikus
téma szerint csoportosítva
ez az egész szakasz teljesíthető 18 hónapon belül
Megkezdett
Befejezett
Nap
Hét
Hónap
Hónapos
Év
Évek
Történelmi
A pátriárkák és a törvény (Mózes öt könyve)
Izrael és Júda történelme
Korai kereszténység
Az Evangéliumok és Apostolok cselekedetei
Költői
Költemények
Prófétai
Főbb próféták
Kisebb próféták
Jelenések
Levelek
Pál levelei
Más levelek
vegyesen
```

**Comment by erykjj** [comment]
Thank you for the translation, @xrtxn
I have made one small adjustment to the last term. Please feel free to report any corrections/improvements ;-)

You can download BRS in Hungarian from https://github.com/erykjj/jwpublib/releases/tag/BRS_3.1 (or the project page).

**Comment by xrtxn** [comment]
Here are a few issues: In hungarian it looks weird in the schedule to say 'hónapok'. It should probably say 'hónapos'.
Also after 'A pátriárkák és a törvény' there is still the english translation '(Pentateuch)' which should translate to 'Mózes öt könyve'.
I made an inconsistency instead of 'Könyvek sorrendje szerint' there should be 'Könyvek sorrendje'.
And apart from this the only thing that looks a little out of place is the page where we select the days, it says 'Nap 8' which looks out of place in hungarian. It works better if we say for example '8. nap', but this isn't a dealbreaker, so if it is not easy to do that no problem.
I will update my original comment.
At last I would like to thank you for this project! I think this will really help me start reading the bible consistently!

**Comment by erykjj** [comment]
Thank you for the corrections, @xrtxn 

I have implemented them. Check out [v3.1a](https://github.com/erykjj/jwpublib/releases/tag/BRS_3.1)

And apologies for "Pentateuch". I added it thinking it was a universal term. Thanks for pointing it out!

Enjoy your Bible reading :-)

**Comment by erykjj** [comment]
I noticed you are also helping with JWLManager translation :-)

That's a big job for one person... Don't overwhelm yourself ;-)

**Comment by xrtxn** [comment]
Thanks for your concern, I'll take a break soon :)
