### ISSUE TITLE
about time line

### ISSUE THREAD

**Issue by a821153070** [erykjj/jwpublib#32]
When will the Chinese version of the timeline be released? Looking forward to it.

**Comment by erykjj** [comment]
Hi @a821153070 

Thank you for your interest.

I will not be releasing this publication in any other language. Every single event would have to be translated. I know it could be done automatically, but I wouldn't be able to check the accuracy of such translation.

Eryk

**Comment by erykjj** [comment]
See https://github.com/erykjj/jwpublib/issues/37
