### ISSUE TITLE
How to translate TBH

### ISSUE THREAD

**Issue by Montanhine** [erykjj/jwpublib#33]
Guys, first of all, thanks for your efforts to share this amazing tool. 
How can I translate to brazilian portughese?

**Comment by erykjj** [comment]
Hi @Montanhine 

First of all, which publication are you referring to? The only one that can be translated is the Bible Reading Schedules, and those are already available in an universal/neutral Portuguese :-)

Eryk

**Comment by Montanhine** [comment]
Hi Erik!
Thank you for your reply.

I was wondering if I could translate all content of "Timeline of Bible
History".

Rafael





Em dom., 10 de mar. de 2024 às 18:58, Eryk J. ***@***.***>
escreveu:

**Comment by erykjj** [comment]
That's a huge undertaking - over 800 strings that could change at any time (as I edit/adjust the wording). And then I would have to enable the translation for other languages also...

More importantly, if you do it, who is going to verify your translation?

**Comment by Montanhine** [comment]
That's a valid point. I don't have someone to verify my translations at the
moment, unfortunately.

Well, thanks for your assistance. I'll continue to use English for now. 🙂

And congratulations on your work! As I mentioned before, it's an awesome
tool!




Em dom., 10 de mar. de 2024 às 21:57, Eryk J. ***@***.***>
escreveu:

**Comment by erykjj** [comment]
I am glad it is useful :-)

I know translation can be done "automatically" with online tools, but in the end someone has to review it for correctness, especially when accuracy is important. And with something this big, it takes a lot of time/effort. I will keep thinking about if/how a translation process can be implemented. Thank you for the suggestion. I will close the issue for now.

**Comment by erykjj** [comment]
See https://github.com/erykjj/jwpublib/issues/37
