### ISSUE TITLE
BRS in Danish

### ISSUE THREAD

**Issue by JohnDoeDK** [erykjj/jwpublib#34]
This is the Danish translation of BRS:

Let me know if there's any issues with it.

`English; Dansk (Danish)
Bible Reading Schedules; Bibellæseplan
Information; Information
Version; Version
More information and updates; Mere information og updates
Canonical; Kanonisk
as found in the Bible; som fundet i Bibelen
Completion; Fuldført
by time of completion of writing; tidspunktet hvor bøgerne er fuldført
Chronological; Kronologisk
in order of historical occurrence; ordnet efter historisk rækkefølge
Thematic; Tematisk
grouped by type of composition; grupperet efter måden bøgerne er skrevet på 
this whole section can be completed within 18 months; hele denne sektion kan fuldføres inden for 18 måneder
Commenced; Påbegyndt
Completed; Fuldført
Day; Dag
Week; Uge
Month; Måned
Months; Måneder
Year; År
Years; År
Historic (PLURAL); Historisk
Patriarchs and the Law (Pentateuch); Patriarkerne og Loven (Pentateuken)
History of Israel and Judah; Israels og Judas Historie
Early Christianity; Tidlig Kristendom
Gospels and Acts; Evangelier og Apostelgerninger
Poetic (PLURAL); Poetiske
Poetic Writings; Poetiske Skrifter
Prophetic (PLURAL); Profetiske
Major Prophets; Store Profeter
Minor Prophets; Små Profeter
Revelation; Åbenbaringen
Letters; Breve
Letters of Paul; Paulus Breve
Other Letters; Andre Breve
combined (AS IN "mixed together"); kombineret`

**Comment by JohnDoeDK** [comment]
Well, that looked funny... 

Here's a file with the translation
[Dansk BRS jwpub.txt](https://github.com/erykjj/jwpublib/files/14616338/Dansk.BRS.jwpub.txt)

**Comment by erykjj** [comment]
Thank you, @JohnDoeDK !

**Comment by erykjj** [comment]
Done. Please check over: https://github.com/erykjj/jwpublib/releases/tag/BRS_3.2
