### ISSUE TITLE
Regarding translation of TBH

### ISSUE THREAD

**Issue by JohnDoeDK** [erykjj/jwpublib#35]
I know you have previously mentioned that this is a huge task. And that future updates could be hard to handle for those who translate for you. 

Could I suggest to you, that you use Crowdin.com for your project? As far as I know, its free. It's easy to update new strings for translation.

**Comment by erykjj** [comment]
Hi @JohnDoeDK 

Yes, I use Weblate for translations on another project. I will give it some thought, but even if I decide to go ahead, nothing will be published until the translation is finished and another person has independently verified everything for accuracy :-)

**Comment by erykjj** [comment]
See https://github.com/erykjj/jwpublib/issues/37
