### ISSUE TITLE
Fix the typo

### ISSUE THREAD

**Issue by jimmy2421** [erykjj/jwpublib#36]
Dear Eryk; 

In the "Timeline of Bible History", there may be a typo: 1920 C.E.‣ ''Leage' of Nations established Wo.

Making these files requires great care, patience and superb skills. Thank you very much ~

Chris

**Comment by erykjj** [comment]
Excellent catch, Chris! Thank you very much for reporting!

**Comment by erykjj** [comment]
Fixed in [TBH_5.1](https://github.com/erykjj/jwpublib/releases/tag/TBH_5.1)
