### ISSUE TITLE
BRS in Portuguese

### ISSUE THREAD

**Issue by Montanhine** [erykjj/jwpublib#38]
Hi!

 I'm opening an issue for this translation as well. 
 For each question I had, I looked up the English expression in the Watchtower library in English, then saw its corresponding in Portuguese.

[BRS - English Português (PT-BR).txt](https://github.com/erykjj/jwpublib/files/14733658/BRS.-.English.Portugues.PT-BR.txt)

**Comment by erykjj** [comment]
Hi @Montanhine 

Thank you, but BRS in Portuguese has been available for a long time. Since there are very few terms, I just made one "universal" Portuguese edition which should be understandable to all (hopefully) :-)
