### ISSUE TITLE
Jwtkn

### ISSUE THREAD

**Issue by yuniermv** [erykjj/jwpublib#4]
Hello brother. I need to know where to get a .jwtkn file for JWBlober or at least know the content of one of them.

**Comment by erykjj** [comment]
I think you're addressing the wrong repo. I have no idea what .jwtkn or JWBlober are.

**Comment by yuniermv** [comment]
Hello. Sorry, it seems that there are different ways to create the
jwpub files. A brother designed a program called JW Blober to edit the
blob files of the jwpub publications database. You have already been
unsubscribed but no one keeps the tokens to use the program. Well, I
don't know if you are a Jehovah's Witness but I would like to create
my own files for JW Library. If you can help me I would appreciate it.
