### ISSUE TITLE
KJV and Strong's Interlinear

### ISSUE THREAD

**Issue by Dan-onymous** [erykjj/jwpublib#40]
Strong's KJV is indexed so that it takes the place of the Kingdom Interlinear. 
This means that the user must choose between two completely different publications, Strong's vs the Kingdom Int.

Is it possible to index it so that it takes the place of the King James Bible?
That way the user can choose between two versions of the same publication, the standard KJ or Strong’s version.

Thank you , Dan

**Comment by erykjj** [comment]
Hi @Dan-onymous

Thank you for your interest in the project and your suggestion...

Believe me, I have tried :-) But, as I mentioned previously (in other issues), I can only get the interlinear (two-line) format to function when I bundle KJS as _int_ (which is the Kingdom Interlinear) - anything else only shows one line. I think that's somehow hard-coded in the app. At least I haven't been able to make it work any other way :-(

Eryk

**Comment by Dan-onymous** [comment]
Thank you @erykjj  
Thought that might be the case, but raised it just in case... :-)

**Comment by erykjj** [comment]
Thanks for understanding. Perhaps in the future JW Library will allow it.

**Comment by elconfa** [comment]
> Hi @Dan-onymous
> 
> Thank you for your interest in the project and your suggestion...
> 
> Believe me, I have tried :-) But, as I mentioned previously (in other issues), I can only get the interlinear (two-line) format to function when I bundle KJS as _int_ (which is the Kingdom Interlinear) - anything else only shows one line. I think that's somehow hard-coded in the app. At least I haven't been able to make it work any other way :-(
> 
> Eryk

Hello, may be possible to install Strong's KJV as another language?

**Comment by erykjj** [comment]
> Hello, may be possible to install Strong's KJV as another language?

Hi @elconfa 

I am not aware of Strong's having been translated into any other languages. _If_ you find such a source, let me know ;-)

**Comment by erykjj** [comment]
> Strong's KJV is indexed so that it takes the place of the Kingdom Interlinear. This means that the user must choose between two completely different publications, Strong's vs the Kingdom Int.
> 
> Is it possible to index it so that it takes the place of the King James Bible? That way the user can choose between two versions of the same publication, the standard KJ or Strong’s version.
> 
> Thank you , Dan

@Dan-onymous 

Please check out the new format: https://github.com/erykjj/jwpublib#kjv-and-strongs-inlineinterlinear
