### ISSUE TITLE
Request: Modern theocratic history

### ISSUE THREAD

**Issue by TonyWenz** [erykjj/jwpublib#41]
Is it possible to have a time-line of modern JW history?
Like:
When did door to door start...
When did we have the first 'drama'.
When did we start have 3 day assembly 
2 day... 1 day
Last 7 day convention
5 day... 3 day RC start.
When did 1hour Public Talks start
Or 45 min and then 30 min Public Talks
When did pio hours change 1k to 850 to 600 hours
When did weekly reports start/stop
S4 Monthly reporting start.
When did we start & stop the Book study
When did Family Worship start.
When did JW Broadcasting start.
GB Updates start
Etc 

This is just a suggestion or request. It is something I research now and then (and more so as my memory fades)
TIA
TonyW

**Comment by erykjj** [comment]
Hi @TonyWenz 

That is a very good idea for a project, and certainly would have _many_ entries if you wanted all that detail :-)

Now, I would not have time to collect all that material into a database. 

BUT, _if_ someone offered to **take the lead**, and perhaps find a team of colaborators/translators...

**Comment by TonyWenz** [comment]
Ty for your response.

I will teach out to a few, and scrape together some dates.

This could be another section (modern Christian history...?)  in your
'Worship' tab.

Talk soon

Agape

TonyW

**Comment by erykjj** [comment]
Hi Tony,

I don't think adding to TBH will be an option - too many modifications, with translations, etc.. We could make it into a separate publication. If you do want to pursue it, I can give you some suggestions regarding the data, etc.
