### ISSUE TITLE
Bible Reading Schedule - Chronological Reading

### ISSUE THREAD

**Issue by benny-danny** [erykjj/jwpublib#43]
The Bible schedule in jwpub is awesome! Love the different ones in 12/18/24/36 months.
Could you consider adding the chronological Bible reading? It would be awesome since it allows us to read in the order in which the events occurred.
I'm attaching a pdf with such schedule. 
[2014-12 Read-Chronological.pdf](https://github.com/user-attachments/files/15994048/2014-12.Read-Chronological.pdf)

**Comment by erykjj** [comment]
Hi @benny-danny 

I'm glad you find the project helpful :-)

Now, I have always wanted to make a truly chronological schedule, but due to lack of resources had to exclude those in favor of a pseudo-chronological order (based on time of completion).

As to your attached schedule, did you make it yourself? How precise/correct is it? Do you have it in another format (Excel, CSV, etc.)?

Also, it may need some adjustments? For instance, JW Library doesn't handle parts of verses - "1Chron. 20:1b-3" will need modification. And some days may be "larger" than others - or have you already checked that?

**Comment by benny-danny** [comment]
Hi @erykjj 
Thanks again for your fast reply.
Regarding your questions, I can answer a few:

> As to your attached schedule, did you make it yourself?
No, used from an app made by a brother (used a few years ago) https://play.google.com/store/apps/details?id=com.mres.schedule&pcampaignid=web_share

> How precise/correct is it?
Can’t saw for sure, but I’ve used it 2 times about 10 years ago for reading it cover to cover and “looks” precise to me. For example, the “Good News According To…” looks pretty close to that schedule and the one in the appendix A7 from the New World translation

> Do you have it in another format (Excel, CSV, etc.)?
No, but if you want I can copy and paste it to a different format. Just let me know what you need.

> Also, it may need some adjustments? For instance, JW Library doesn't handle parts of verses - "1Chron. 20:1b-3" will need modification.
Yes, I understand that, but that shouldn’t be an issue for “the reader” since sometimes publications also have 1b or 1a, and they show the complete verse. It’s up to the reader to “divide” the verse.

> And some days may be "larger" than others - or have you already checked that?
I’ve followed that schedule 2 times in the past (and also my mom as well). I think it’s well divided for a 12 months schedule, but probably there are days that are a bit “larger” than the other… can’t tell for sure.

Let me know if you need anything else.

**Comment by erykjj** [comment]
Well, how do you feel about taking this into your hands and preparing it for me? To start with, I would need a CSV (or Excel if that's easier) with the scriptures for each day (I don't need the dates, just each day on a separate line). Once I have that, I will do an automatic check for completeness and balance. Then we'll go from there.

**Comment by benny-danny** [comment]
> Well, how do you feel about taking this into your hands and preparing it for me? To start with, I would need a CSV (or Excel if that's easier) with the scriptures for each day (I don't need the dates, just each day on a separate line). Once I have that, I will do an automatic check for completeness and balance. Then we'll go from there.

Hi! See if this works. 
[Chronolog Reading.xlsx](https://github.com/user-attachments/files/16018274/Chronolog.Reading.xlsx)

**Comment by erykjj** [comment]
Please see your invite to another repo
