### ISSUE TITLE
Cooperate

### ISSUE THREAD

**Issue by livrasand** [erykjj/jwpublib#5]
Hello, I am a JWPUB file creator too, I would like to distribute my files in your repository and be a contributor. I would be a contributor in Spanish. I am a theocratic software creator too, you can check my website at goattendant.com. I have a WhatsApp group where I share my files, but maybe with your repository I can reach more people. Let me know if you agree, otherwise don't answer and just close the Issue. I'm just looking for distribution.

**Comment by erykjj** [comment]
Hi @livrasand . Thank you for your message.

First, I don't understand why you don't set up your own Github repo if that's what you want. Personally, I don't view Github as a means to "reach more people" - it's not a social network.

Second, I don't know what kind of material you would like to contribute, but I'm rather sensitive about copyrights, and want to be personally responsible for what _I_ share.

For those two reasons, I will decline your offer.
