### ISSUE TITLE
I want korean BRS

### ISSUE THREAD

**Issue by kaniza459** [erykjj/jwpublib#50]
I need a BRS in Korean. Please make it in Korean, too

한국어 Korea (DESTINATION LANGUAGE)
성서 읽기 일정
정보
버전
자세한 정보 및 업데이트
정준
성서에 나와 있는 바와 같이
완료
집필이 끝날 무렵에
연대순
역사적으로 보아
주제
유형별로 그룹화 구성
이 전체 섹션은 18개월 이내에 완료할 수 있습니다
시작
완료
일
주일
달
몇달
연
몇 해
역사 (PLURAL)
총대주교와 율법(Pentateuch)
이스라엘과 유다의 역사
초기 기독교
복음서와 사도행전
시 (PLURAL)
시적인 글
예언 (PLURAL)
주요 예언자들
작은 예언자들
계시록
편지들
바울의 편지
기타 문자
결합 (AS IN "함께 혼합")

**Comment by erykjj** [comment]
Duplicate of https://github.com/erykjj/jwpublib/issues/21
