### ISSUE TITLE
How To...

### ISSUE THREAD

**Issue by szxyks** [erykjj/jwpublib#57]
I'd like to thank you for these amazing jwpublib. I enjoyed them so much.

My question is this: If you want to create my own jwpub how can I do that. What programming language do I need and how do I package everything into a jwpub extension.

Would you be able to provide with me a step-by-step tutorials? Something simple like creating a simple "Hello World" jwpub, which will contains a couple of tabs, with links, images, etc.

**Comment by erykjj** [comment]
Hi @szxyks 
I think you have been around Github enough to know how to search through [Issues](https://github.com/erykjj/jwpublib/issues?q=is%3Aissue). Had you done so, you would have seen my stance on requests such as this one... In any case, please refer to the last paragraph in the intro of the [Readme](https://github.com/erykjj/jwpublib).
