### ISSUE TITLE
Fth in Italian

### ISSUE THREAD

**Issue by GTNW73** [erykjj/jwpublib#58]
Hallo brothers. Is possible in italian language?

**Comment by erykjj** [comment]
Hi @GTNW73 

Which publication?

**Comment by GTNW73** [comment]
Fede in cammino  ... brother Mc MillanInviato dal mio Galaxy
-------- Messaggio originale --------Da: "Eryk J." ***@***.***> Data: 03/10/24  14:32  (GMT+02:00) A: erykjj/jwpublib ***@***.***> Cc: GTNW73 ***@***.***>, Mention ***@***.***> Oggetto: Re: [erykjj/jwpublib] Italian language. Is possibble? (Issue #58) 
Hi @GTNW73
Which publication?

**Comment by erykjj** [comment]
If you can find a good quality translation, perhaps it can be done.

**Comment by GTNW73** [comment]
Hello .... yes i havep.s. excuse my broken englishInviato dal mio Galaxy
-------- Messaggio originale --------Da: "Eryk J." ***@***.***> Data: 03/10/24  15:03  (GMT+01:00) A: erykjj/jwpublib ***@***.***> Cc: GTNW73 ***@***.***>, Mention ***@***.***> Oggetto: Re: [erykjj/jwpublib] Fth in Italian (Issue #58) 
If you can find a good quality translation, perhaps it can be done.

**Comment by erykjj** [comment]
Please attach it here so I can see if it can be adapted.

**Comment by GTNW73** [comment]
i have here attached in pdf versionInviato dal mio Galaxy
-------- Messaggio originale --------Da: "Eryk J." ***@***.***> Data: 03/10/24  17:44  (GMT+01:00) A: erykjj/jwpublib ***@***.***> Cc: GTNW73 ***@***.***>, Mention ***@***.***> Oggetto: Re: [erykjj/jwpublib] Fth in Italian (Issue #58) 
Please attach it here so I can see if it can be adapted.

**Comment by erykjj** [comment]
Sorry, no attachment :-/ You may have to do it directly on Github.

**Comment by GTNW73** [comment]
[1955 Mac Millan. Fede in cammino JW.pdf](https://github.com/user-attachments/files/17247397/1955.Mac.Millan.Fede.in.cammino.JW.pdf)

**Comment by GTNW73** [comment]
attached

**Comment by erykjj** [comment]
Thank you, @GTNW73 , but this won't work. I cannot get quality text out of this document...

If you can find me the original text (MS Word or something like that) used to produce this PDF, then I might be able to adapt it. Otherwise, sorry :-(

**Comment by GTNW73** [comment]
[1955 Mac Millan. Fede in cammino JW.docx](https://github.com/user-attachments/files/17249308/1955.Mac.Millan.Fede.in.cammino.JW.docx)
Thiu is in word format. Thanks

**Comment by erykjj** [comment]
Sorry, but this looks just as bad as the PDF:
![2024-10-03_15-49-17](https://github.com/user-attachments/assets/cbc07a66-448a-4b76-b7aa-410c0341eb1c)
It would be too much work fixing all the spelling/formatting/etc.

**Comment by GTNW73** [comment]
Buon giorno,

   Sto provando a sistemarlo in word meglio. Appena finisco il lavoro te lo
giro. Grazie.

P.S. Sarebbe più facile caricare ebook in formato EPUB? eBook di Giuseppe
Flavio in italiano e diTertulliano?

Il giorno gio 3 ott 2024 alle 21:50 Eryk J. ***@***.***> ha
scritto:

**Comment by erykjj** [comment]
Hi @GTNW73 

ebooks _may_ be better; it all depends on the source they were based on. If the source was poor quality; so is the ebook - generally.

As for Josephus/Tertulian in Italian, let's do one thing first: Faith :-)

And, if you're going to fix the MS Word, I would rather you made it into markdown files - one for each chapter and instead of rich-text formatting, use this, please:
```
# HEADING IN UPPERCASE

|small-caps at start of chapter|

^note number^

_italics_

\```
quoted section
\```

«flush to left
»indent

… ellipsis instead of ...
```
