### ISSUE TITLE
More Books

### ISSUE THREAD

**Issue by TomVanReeth** [erykjj/jwpublib#59]
Hi 

If you want i can provide more books for getting in the app. 
During corona i scan all my books, and have them in pdf. But i don't now how i can make them ready for the app.
I scan hole my theocratic library. I think i did it for more than 500 books. Most in Dutch but also in English. 
Could we do somethin with this....

Kind regards Tom

**Comment by erykjj** [comment]
Hello @TomVanReeth 

Thank you for your offer.

The issue/difficulty is not so much in obtaining the material. It's just that PDF's or other scanned images, even if processed through OCR, are difficult to work with. They (most likely) contain errors (from the OCR process) and have no formatting markup.

**Comment by TomVanReeth** [comment]
Hi Eryk, 

 

I’m my books transfering into html and epub file. 

Is that something to handle?

 

Kind regards, 

 

Tom

 

Van: Eryk J. ***@***.***> 
Verzonden: vrijdag 25 oktober 2024 22:15
Aan: erykjj/jwpublib ***@***.***>
CC: TomVanReeth ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [erykjj/jwpublib] More Books (Issue #59)

 

Hello @TomVanReeth <https://github.com/TomVanReeth> 

Thank you for your offer.

The issue/difficulty is not so much in obtaining the material. It's just that PDF's or other scanned images, even if processed through OCR, are difficult to work with. They (most likely) contain errors (from the OCR process) and have no formatting markup.

**Comment by erykjj** [comment]
HTML is (usuall) ok.

What book(s) are you thinking of? Is it copyrighted still?

**Comment by TomVanReeth** [comment]
Hi 

 

i have a lot of books, many in dutch but also a lot in englisch espaccialy bible translations and bible references most without copyrighted 

 

Van: Eryk J. ***@***.***> 
Verzonden: vrijdag 25 oktober 2024 23:13
Aan: erykjj/jwpublib ***@***.***>
CC: TomVanReeth ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [erykjj/jwpublib] More Books (Issue #59)

 

HTML is (usuall) ok.

What book(s) are you thinking of? Is it copyrighted still?

**Comment by erykjj** [comment]
Tom, before you get too excited :-)

I won't include publications that I don't feel would be very useful to me. If there is a book you think would be a good add-on for JW Library, convice me ;-)

**Comment by TomVanReeth** [comment]
On this topic i search on github and i find a method for thé books but i
don't think you Will use this method from a brother. But im not qualified
in programming. But Well interested. So you see i'm a prutser like they say
in dutch. But verry curious

Op vr 25 okt 2024 23:21 schreef Eryk J. ***@***.***>:

**Comment by erykjj** [comment]
@TomVanReeth 

Let's put this on the back-burner for now. I wouldn't be able to handle another project at the moment. Thank you for your willingness to contribute material :-)

**Comment by TomVanReeth** [comment]
Are you in the opprtunity to tell me with tools you use for that kind off project?

**Comment by erykjj** [comment]
Sorry, @TomVanReeth , I cannot reply to that.

**Comment by TomVanReeth** [comment]
Hi Eryk, 
The translation is toppie

**Comment by erykjj** [comment]
> The translation is toppie

???
