### ISSUE TITLE
Please translate to Spanish 

### ISSUE THREAD

**Issue by IsraReyna** [erykjj/jwpublib#6]
Please JW Bible scheduled read

**Comment by erykjj** [comment]
Will do. I just have to finish some other projects first ;-)

**Comment by erykjj** [comment]
Hecho! Lo puedes encontrar [aquí](https://github.com/erykjj/jwpublib/releases/tag/BRS_1.2). Favor avisarme si encuentras algún problema con el archivo ;-)

**Comment by IsraReyna** [comment]
Wooow que rapidez…. Excelente trabajo. Muchas gracias. El 3 feb 2023, a la(s) 5:29 p.m., Eryk J. ***@***.***> escribió:﻿
Hecho! Lo puedes encontrar aquí. Favor avisarme si encuentras algún problema con el archivo ;-)

**Comment by erykjj** [comment]
Sí, se pudo hacer más fácilmente de lo que pensaba. Espero te sirva.

**Comment by erykjj** [comment]
Sí, pero no vamos a hablar de eso. Gracias por tu comprensión.
