### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by TomVanReeth** [erykjj/jwpublib#60]
Hi i can help if nessasary in dutch language. 

Give a hug 

Kind regards Tom

**Comment by erykjj** [comment]
Hi @TomVanReeth 

Thank you for you offer to help :-)

I have three projects that could be translated into Dutch. In order or difficulty, they are _Who Wants to Be a Missionary?_ (BaM), _God's Prophetic Word_ (GPW), and _Timeline of Bible History_ (TBH). You tell me which one you think you can handle ;-)

Eryk

**Comment by TomVanReeth** [comment]
Hi Eryk, 

 

If you want i can start with the most easy onde. 

 

Let me now

 

Kind regards, 

 

Tom

 

Van: Eryk J. ***@***.***> 
Verzonden: vrijdag 25 oktober 2024 22:12
Aan: erykjj/jwpublib ***@***.***>
CC: TomVanReeth ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [erykjj/jwpublib] Translations (Issue #60)

 

Hi @TomVanReeth <https://github.com/TomVanReeth> 

Thank you for you offer to help :-)

I have three projects that could be translated into Dutch. In order or difficulty, they are Who Wants to Be a Missionary? (BaM), God's Prophetic Word (GPW), and Timeline of Bible History (TBH). You tell me which one you think you can handle ;-)

Eryk

**Comment by erykjj** [comment]
@TomVanReeth ,

Here is the BaM project: https://crowdin.com/project/bam-quiz/nl

You should be able to log in with your GitHub account. Let me know if you have any issues.

Thanks!

**Comment by TomVanReeth** [comment]
Hi Eryk, 

 

The translation is done. 

You could take a look at it. 

 

For the books, i have for example a Flavius josephus in dutch. 

If you have the time and you want to learn me a bit i can give my hands to help . 

 

Just teach me and i will do a lot of the job in advanced so that you dont have do much. 



It is my offer….

 

 

Kind regards

 

Tom

 

 

Van: Eryk J. ***@***.***> 
Verzonden: vrijdag 25 oktober 2024 23:16
Aan: erykjj/jwpublib ***@***.***>
CC: TomVanReeth ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [erykjj/jwpublib] Translations (Issue #60)

 

@TomVanReeth <https://github.com/TomVanReeth>  ,

Here is the BaM project: https://crowdin.com/project/bam-quiz/nl

You should be able to log in with your GitHub account. Let me know if you have any issues.

Thanks!

**Comment by erykjj** [comment]
@TomVanReeth 
I can only see a few of the strings translated. Did I miss something?

**Comment by TomVanReeth** [comment]
I translated 2 pages

 

 

Van: Eryk J. ***@***.***> 
Verzonden: zaterdag 26 oktober 2024 13:29
Aan: erykjj/jwpublib ***@***.***>
CC: TomVanReeth ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [erykjj/jwpublib] Translations (Issue #60)

 

@TomVanReeth <https://github.com/TomVanReeth> 
I can only see a few of the strings translated. Did I miss something?

**Comment by erykjj** [comment]
Did you hit SAVE after each modification?

**Comment by erykjj** [comment]
Your translation for "Who Wants to Be a Missionary?" is empty ;-)

**Comment by erykjj** [comment]
OK. I see it is done now. I will later send you a release candidate version so you can have a look at your strings in context. But that will be later on. Take a break in the mean time :-)

**Comment by TomVanReeth** [comment]
Ik hope you Will find it good.

Op za 26 okt 2024 13:42 schreef Eryk J. ***@***.***>:

**Comment by erykjj** [comment]
I managed to do it before I have to go...

[BaM_RC_O.zip](https://github.com/user-attachments/files/17530426/BaM_RC_O.zip)
Just change the extension to .jwpub

Please make any necessary adjustments on crowdin.com and approve the strings that are correct.

Also, what name/handle should I use on the credits page to give you credit for the translation?

**Comment by TomVanReeth** [comment]
A brother who loves the truth
For me non credits.

Op za 26 okt 2024 14:07 schreef Eryk J. ***@***.***>:

**Comment by erykjj** [comment]
As you wish.

So, would you say that with the changes you made it's ready to release into the wild? Or would you like to see another release candidate first?

**Comment by TomVanReeth** [comment]
Or would you like to see another release candidate first?

Let us do ths first

 

Van: Eryk J. ***@***.***> 
Verzonden: zaterdag 26 oktober 2024 18:16
Aan: erykjj/jwpublib ***@***.***>
CC: TomVanReeth ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [erykjj/jwpublib] Translations (Issue #60)

 

As you wish.

So, would you say that with the changes you made it's ready to release into the wild? Or would you like to see another release candidate first?

**Comment by erykjj** [comment]
[BaM_RC2_O.zip](https://github.com/user-attachments/files/17531277/BaM_RC2_O.zip)

Please let me know if it's good to go. If not, please adjust again on crowdin.com

**Comment by erykjj** [comment]
Hi @TomVanReeth 

I have released BaM in Dutch. Thank you very much for your help!

I will close this issue. For communication regarding translations for the other projects, please use one of the threads [here](https://github.com/erykjj/jwpublib/issues?q=is%3Aissue+is%3Aopen+label%3Acollaboration+translation).
