### ISSUE TITLE
Translate BRS in Polish

### ISSUE THREAD

**Issue by Goykew** [erykjj/jwpublib#8]
Hello. I'm from Poland. I am from the Siemiatycze congregation. Please translate BRS into Polish. Can I help with that? Please

**Comment by erykjj** [comment]
Can you translate the following strings into Polish for me, please?

```
Day
Week
Commenced
Completed
Bible Reading Schedules
month
year
months
years
Canonical
Chronological
Completed
Version
as found in the Bible
in order of historical occurrence
by time of completion of writing
More information and updates
```

**Comment by Goykew** [comment]
Dzień
Tydzień
Data rozpoczęcia
Data zakończenia
Plan Czytania Biblii
miesiąc
rok
miesięcy
lata
Według kolejności ksiąg
Chronologiczny
Według spisania ksiąg
Wersja
tak jak są ułożone księgi w Biblii
wydarzenia ułożone chronologicznie
według czasu ukończenia spisywania księgi
Więcej informacji i aktualizacji

**Comment by Goykew** [comment]
Dzień
Tydzień
Data rozpoczęcia
Data zakończenia
Plan Czytania Biblii
miesiąc
rok
miesięcy
lata
Według kolejności ksiąg
Chronologiczny
Według spisania ksiąg
Wersja
tak jak są ułożone księgi w Biblii
wydarzenia ułożone chronologicznie
według czasu ukończenia spisywania księgi
Więcej informacji i aktualizacji

**Comment by Goykew** [comment]
Dzień
Tydzień
Data rozpoczęcia
Data zakończenia
Plan Czytania Biblii
miesiąc
rok
miesięcy
lata
Według kolejności ksiąg 
Chronologiczny
Według spisania ksiąg
Wersja
tak jak są ułożone księgi w Biblii
wydarzenia ułożone chronologicznie
według czasu ukończenia spisywania księgi
Więcej informacji i aktualizacji

**Comment by Goykew** [comment]
Dzień
Tydzień
Data rozpoczęcia
Data zakończenia
Plan Czytania Biblii
miesiąc
rok
miesięcy
lata
Według kolejności ksiąg
Chronologiczny
Według spisania ksiąg
Wersja
tak jak są ułożone księgi w Biblii
wydarzenia ułożone chronologicznie
według czasu ukończenia spisywania księgi
Więcej informacji i aktualizacji

**Comment by Goykew** [comment]
Dzień
Tydzień
Data rozpoczęcia:
Data zakończenia:
Plan Czytania Biblii
miesiąc
rok
miesięcy
lata
Według kolejności ksiąg
Chronologiczny
Według spisania ksiąg
Wersja
tak jak są ułożone księgi w Biblii
wydarzenia ułożone chronologicznie
według czasu ukończenia spisywania księgi
Więcej informacji i aktualizacji

**Comment by Goykew** [comment]
Day
Week
Commenced
Completed
Bible Reading Schedules
month
year
months
years
Canonical
Chronological
Completed
Version
as found in the Bible
in order of historical occurrence
by time of completion of writing
More information and updates

**Comment by Goykew** [comment]
Dzień
Tydzień
Data rozpoczęcia
Data zakończenia
Plan Czytania Biblii
miesiąc
rok
miesięcy
lata
Według kolejności ksiąg
Chronologiczny
Według spisania ksiąg
Wersja
tak jak są ułożone księgi w Biblii
wydarzenia ułożone chronologicznie
według czasu ukończenia spisywania księgi
Więcej informacji i aktualizacji

**Comment by erykjj** [comment]
That looks quite right :-)

Just a question: the last one shouldn't it be "Więcej informacji i aktualizacje"? It's a link to the repo

And I don't know why your replies keep disappearing?!

**Comment by Goykew** [comment]
Updates. It may or may not be an "e" at the end. The meaning is the same. disappeared because something wrong pasted the rulers and I had to remove them. :) But I already know where the mistake was. That will no longer be the case. I cordially greet and thank you for your help

**Comment by erykjj** [comment]
Is there **one word** that describes _Canonical_ and _Completed_ (just like you did with _Chronological_)? It doesn't have to be a literal translation, as long as the distinct meanings are preserved.

**Comment by erykjj** [comment]
Also, @Goykew , I have another project that could use some help translating, but it's more involved and so I'm using [Weblate](https://hosted.weblate.org/engage/jwlmanager/) for it.

Do you think you'd be willing to work at it at your own time? No rush. If so, I would add Polish as a language to [JWLManager](https://github.com/erykjj/jwlmanager).

**Comment by erykjj** [comment]
@Goykew , please try this: [BRS_P_beta.zip](https://github.com/erykjj/jwpublib/files/10715053/BRS_P_beta.zip)  - just unzip it to get the .jwpub

Let me know if you observe anything that needs to be modified before releasing on official version.

Thank you!

**Comment by erykjj** [comment]
@Goykew , have you had a chance to verify the translation in the beta I sent you? Is it OK to publish as official?

**Comment by Goykew** [comment]
Sorry for only now replying.  a lot of tasks.

The plan of reading the Bible according to how the books are arranged in the Bible can be described in one word "Canonical".  Ale is a rarely used word in Poland (but it can be).  However, the plan of reading according to how the writing of the books was completed cannot be described in one word.  The shortest is "According to writing" but you will have to look at the description because it is not entirely clear what is going on.
 I would correct the change from uppercase to lowercase (details in the photo).  In Poland, we do not write with a capital letter after a number. I can help with translation in another project


Pozdrawiam serdecznie🙂
Władek Goyke

**Comment by erykjj** [comment]
Hi Władek, thank you for your input, but I don't see any photo, so I'm not sure which "change from uppercase to lowercase" you're refrerring to ??

**Comment by erykjj** [comment]
As to the other project, here are the translation strings, etc.: https://hosted.weblate.org/languages/pl/jwlmanager/

It's a bit more involved, but there are some useful tools on the website as well.

Let me know if you don't understand something. This is for my JWLManager app, so you can have a look at it to see where/how the strings are used.

Thanks in advance for any help you can render ;-)

Eryk

**Comment by Goykew** [comment]
> Cześć Władek, dziękuję za wkład, ale nie widzę żadnego zdjęcia, więc nie jestem pewien, którą "zmianę z wielkich na małe" refrerring do ??
![IMG_1986](https://user-images.githubusercontent.com/44505473/222531716-fcca22e2-c05f-4ce6-8b1a-8198a8dd58f0.jpg)

**Comment by erykjj** [comment]
Please unzip and test. I have made a few more corrections which apply to other languages as well, so once you confirm the translation, I can release the update for all.

[BRS_P.zip](https://github.com/erykjj/jwpublib/files/10875588/BRS_P.zip)

**Comment by erykjj** [comment]
Hi @Goykew , there are some additional strings that need translation into Polish. Would you be able to do those for me, please?

https://github.com/erykjj/jwpublib/issues/21

**Comment by Goykew** [comment]
will do it within days. We have a convention this weekend. will do it after
ok?


sob., 1 lip 2023 o 23:00 Eryk J. ***@***.***> napisał(a):

**Comment by erykjj** [comment]
Yes, of course. Thank you and enjoy the convention (though it's probably over by now :-)

**Comment by erykjj** [comment]
@Goykew , I did the remaining translation online so as to release the Polish version along with the rest. Still, when you have a moment, please check it over and let me know if/what needs correcting. Thank you again!
